name: gazelle
# channels:
#   - nvidia
#   - pytorch
#   - conda-forge
#   - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  - timm
  - scikit-learn
  - matplotlib
  - pandas
  